name: Deploy FastAPI to Ubuntu Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test commands here if you have any
        echo "Running tests..."

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/parallel/backend
          
          # Stop the service if running
          sudo systemctl stop fastapi-backend || true
          
          # Pull latest changes
          git pull origin main
          
          # Update virtual environment
          source parallel/bin/activate
          pip install -r requirements.txt
          deactivate
          
          # Restart the service
          sudo systemctl daemon-reload
          sudo systemctl start fastapi-backend
          
          # Check service status
          sudo systemctl status fastapi-backend
          
          # Verify deployment
          curl -I http://127.0.0.1:8000/ || true
