name: Deploy FastAPI to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
  QDRANT_URL: ${{ secrets.QDRANT_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/ || echo "Tests failed but continuing deployment"

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.VPS_PORT }} \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "
            # Environment variables
            export COLLECTION_NAME='${{ secrets.COLLECTION_NAME }}'
            export GOOGLE_API_KEY='${{ secrets.GOOGLE_API_KEY }}'
            export QDRANT_API_KEY='${{ secrets.QDRANT_API_KEY }}'
            export QDRANT_URL='${{ secrets.QDRANT_URL }}'
            
            # Deployment commands
            cd /var/www/parallel/backend
            git pull origin main
            source parallel/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-backend
            echo 'Deployment completed successfully'
          "
